security:

    providers:
        in_memory:
            memory:
                users:
                    alice:
                        # password: meQGmPFCP5Ul
                        password: $2y$12$wvdE1Fjb29hgY6//g/khuedLq3wQOuLbZ/tYqzxI9PfIfBF24fEfa
                        roles: 'ROLE_USER'
                    john:
                        # password: 1L6lllW9zXg0
                        password: $2y$12$DFozWehwPkp14sVXr7.IbusW8ugvmZs9dQMExlggtyEa/TxZUStnO
                        roles: 'ROLE_ADMIN'
                    # php bin/console security:encode-password
        foggyline_customer:
            entity:
                class: FoggylineCustomerBundle:Customer
#                class: Foggyline\CustomerBundle\Entity\Customer
                property: username

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
        Foggyline\CustomerBundle\Entity\Customer:
            algorithm: bcrypt
            cost: 12

    firewalls:



        foggyline_customer:
            anonymous: ~
#            pattern: /customer/edit
#            http_basic:
            provider: foggyline_customer
            form_login:
                login_path: foggyline_customer_login
                check_path: foggyline_customer_login

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~



    access_control:
        # exclude /login path from firewall
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # protect any possible auto-generated CRUD actions from everyone's access
        - { path: /new, roles: ROLE_ADMIN }
        - { path: /edit, roles: ROLE_ADMIN }
        - { path: /, roles: ROLE_ADMIN, methods: [DELETE] }
